{{- if .Values.ingress.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
      - name: {{ .name }}
      {{- end }}
      {{- end }}
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        ports:
        - containerPort: {{ .Values.backend.service.port }}
        env:
        - name: DB_URL
          value: "postgres://{{ .Values.db.user }}:{{ .Values.db.password }}@{{ .Release.Name }}-db:5432/{{ .Values.db.name }}?sslmode=disable"
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-oauth-secret
              key: google-client-id
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-oauth-secret
              key: google-client-secret
        - name: GOOGLE_REDIRECT_URL
          value: "https://{{ (index .Values.ingress.hosts 0).host }}/auth/callback"
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-oauth-secret
              key: jwt-secret-key
{{- end }} 